name: R-CMD-check

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev

      - name: Install remotes package
        run: Rscript -e 'install.packages("remotes")'

      - name: Install binostics package (not on CRAN)
        run: Rscript -e 'remotes::install_github("cran/binostics")'

      - name: Install package dependencies manually (to avoid binostics issue)
        run: Rscript -e 'remotes::install_deps(dependencies = TRUE)'

      - name: Install rcmdcheck
        run: Rscript -e 'install.packages("rcmdcheck")'

      - name: Run R CMD check
        run: Rscript -e 'rcmdcheck::rcmdcheck(error_on = "error")'

